- hosts: localhost
  gather_facts: no
  remote_user: ubuntu
  become: yes
  tasks:

  - name: Creating network for topology 
    docker_network:
      name: "{{bridgeName}}"
      ipam_options:
        subnet: "{{ipCidr}}"
        iprange: "{{ipCidr}}"